// <auto-generated />
namespace SCMS.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class usersinroles : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(usersinroles));
        
        string IMigrationMetadata.Id
        {
            get { return "201409120352453_usersinroles"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
